import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Snowdrop
        </h1>

        <span className={styles.alt}>Coming soon</span>
      </main>

      <footer className={styles.footer}>
        
        <pre>
          Snowdrop by Mohamed Omar
          <br />
          NextJS, Strapi, Postgres
        </pre>
      </footer>
    </div>
  )
}
